const express = require('express')
const BodyParser = require('body-parser')
const morgan = require('morgan')
const cors = require('cors')
const dotenv = require('dotenv')

dotenv.config()
const { APP_PORT } = process.env

const app = express()

app.use(BodyParser.urlencoded())
app.use(morgan('dev'))
app.use(cors('*'))
app.use('/uploads', express.static('uploads'))
app.use('/movies', require('./src/routes/movies'))
app.use('/movies/:id', require('./src/routes/movies'))
app.use('/genre', require('./src/routes/genre'))
app.use('/genre/:id', require('./src/routes/genre'))
app.use('/cinemas', require('./src/routes/cinemas'))
app.use('/cinemas/:id', require('./src/routes/cinemas'))
app.use('/transaction', require('./src/routes/transaction'))
app.use('/admin/movies', require('./src/routes/MoviesAdmin'))
app.use('/admin/movies/:id', require('./src/routes/MoviesAdmin'))
app.use('/admin/cinemas/', require('./src/routes/cinemaByAdmin'))
app.use('/admin/cinemas/:id', require('./src/routes/cinemaByAdmin'))
app.use('/admin/genre', require('./src/routes/genreByAdmin'))
app.use('/admin/genre/:id', require('./src/routes/genreByAdmin'))
app.use('/admin/seat/', require('./src/routes/seatByAdmin'))
app.use('/admin/seat/:id', require('./src/routes/seatByAdmin'))
app.use('/admin/shw-time/', require('./src/routes/showTimeAdmin'))
app.use('/admin/shw-time/:id', require('./src/routes/showTimeAdmin'))

app.listen(APP_PORT, () => {
  console.log(`Application is running opn port ${APP_PORT}`)
})
