module.exports = [
  {
    id: 1,
    language: 'en',
    genre: 'Action, Sci-Fi, Mystery',
    director: 'Benjamin Lucas',
    actors: 'Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel',
    name: 'Wonder Woman 1984',
    synopsis: 'Wonder Woman comes into conflict with the Soviet Union during the Cold War in the 1980s and finds a formidable foe by the name of the Cheetah.',
    relaseDate: '2020-12-16',
    runtime: '131 min',
    popularity: 3280252,
    poster: 'https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg',
    cinema: 'Cinemex, Hiflix, CineOne, CinemaXXI, Cinebay, Olympia Cinema'
  },
  {
    id: 2,
    language: 'en',
    genre: 'Action, Sci-Fi, Mystery',
    director: 'James Jonathan',
    actors: 'Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel',
    name: 'Soul',
    synopsis: 'Joe Gardner is a middle school teacher with a love for jazz music. After a successful gig at the Half Note Club, he suddenly gets into an accident that separates his soul from his body and is transported to the You Seminar, a center in which souls develop and gain passions before being transported to a newborn child. Joe must enlist help from the other souls-in-training, like 22, a soul who has spent eons in the You Seminar, in order to get back to Earth.',
    relaseDate: '2020-12-25',
    runtime: '130 min',
    popularity: 274369,
    poster: 'https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg',
    cinema: 'Cinemex, Hiflix, CineOne, Cinebay, Olympia Cinema'
  },
  {
    id: 3,
    language: 'en',
    genre: 'Action, Sci-Fi, Mystery',
    director: 'Jacob Hanson',
    actors: 'Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel',
    name: 'The Croods: A New Age',
    synopsis: 'Searching for a safer habitat, the prehistoric Crood family discovers an idyllic, walled-in paradise that meets all of its needs. Unfortunately, they must also learn to live with the Bettermans -- a family thats a couple of steps above the Croods on the evolutionary ladder. As tensions between the new neighbors start to rise, a new threat soon propels both clans on an epic adventure that forces them to embrace their differences, draw strength from one another, and survive together.',
    relaseDate: '2020-11-25',
    runtime: '126 min',
    popularity: 1161894,
    poster: 'https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg',
    cinema: 'Cinemex, Hiflix, CineOne, CinemaXXI, Cinebay'
  },
  {
    id: 4,
    language: 'en',
    genre: 'Action, Sci-Fi',
    director: 'Stave Job',
    actors: 'Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel',
    name: 'Breach',
    synopsis: 'A hardened mechanic must stay awake and maintain an interstellar ark fleeing the dying planet Earth with a few thousand lucky souls on board... the last of humanity. Unfortunately, humans are not the only passengers. A shapeshifting alien creature has taken residence, its only goal is to kill as many people as possible. The crew must think quickly to stop this menace before it destroys mankind.',
    relaseDate: '2020-12-17',
    runtime: '138 min',
    popularity: 990618,
    poster: 'https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg',
    cinema: 'CineOne, CinemaXXI, Cinebay, Olympia Cinema'
  },
  {
    id: 5,
    language: 'en',
    genre: 'Action, Sci-Fi',
    director: 'Jhon Wathan',
    actors: 'Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel',
    name: 'Roald Dahls The Witches',
    synopsis: 'In late 1967, a young orphaned boy goes to live with his loving grandma in the rural Alabama town of Demopolis. As the boy and his grandmother encounter some deceptively glamorous but thoroughly diabolical witches, she wisely whisks him away to a seaside resort. Regrettably, they arrive at precisely the same time that the worlds Grand High Witch has gathered.',
    relaseDate: '2020-10-25',
    runtime: '140 min',
    popularity: 433856,
    poster: 'https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg',
    cinema: 'Cinemex, Hiflix, CineOne, CinemaXXI,'
  },
  {
    id: 6,
    language: 'en',
    genre: 'Action, Sci-Fi, Romance',
    director: 'Popper jene',
    actors: 'Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel',
    name: 'Chick Fight',
    synopsis: 'When Anna Wyncomb is introduced to an an underground, all-female fight club in order to turn the mess of her life around, she discovers she is much more personally connected to the history of the club than she could ever imagine.',
    relaseDate: '2021-02-04',
    runtime: '139 min',
    popularity: 335152,
    poster: 'https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg',
    cinema: 'CinemaXXI, Cinebay, Olympia Cinema'
  },
  {
    id: 7,
    language: 'en',
    genre: 'Comedy',
    director: 'Jhon Steve',
    actors: 'Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel',
    name: 'Playhouse',
    synopsis: 'Reckless Jack Travis is an irreverent horror writer notorious for scaring audiences. But as he obsesses over creating a new theatre show set in a haunted Scottish castle, demonic disturbances from deep within the walls begin to prey on his troubled daughter. When the alarming supernatural forces start to close in on him too, Jack is forced to reckon with the terrifying consequences of creating such a dark and macabre play. But will he realise the danger of unearthing a historic curse and stop writing before he damns himself, his personal sanity and those he loves forever?',
    relaseDate: '2021-01-28',
    runtime: '131 min',
    popularity: 204297,
    poster: 'https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg',
    cinema: 'CinemaXXI, Cinebay, Olympia Cinema'
  },
  {
    id: 8,
    language: 'en',
    genre: 'Drama, Romance',
    director: 'Hamas Tandon',
    actors: 'Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel',
    name: 'Monster Hunter',
    synopsis: 'A portal transports Lt. Artemis and an elite unit of soldiers to a strange world where powerful monsters rule with deadly ferocity. Faced with relentless danger, the team encounters a mysterious hunter who may be their only hope to find a way home.',
    relaseDate: '2020-12-03',
    runtime: '122 min',
    popularity: 147842,
    poster: 'https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg',
    cinema: 'Cinemex, Cinebay, Olympia Cinema'
  },
  {
    id: 9,
    language: 'en',
    genre: 'Sci-Fi, Romance',
    director: 'Jacky Walson',
    actors: 'Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel',
    name: 'Death of Me',
    synopsis: 'A couple on holiday on a remote South Pacific island awaken one morning with a hang over and no recollection of what transpired. When playing back a video of the previous night, they see they participated in a local ritual that somehow ends with him murdering her.',
    relaseDate: '2020-10-02',
    runtime: '127 min',
    popularity: 135443,
    poster: 'https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg',
    cinema: 'Cinemex, Hiflix, CineOne'
  },
  {
    id: 10,
    language: 'en',
    genre: 'Horor',
    director: 'Doni yen',
    actors: 'Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel',
    name: 'The Silencing',
    synopsis: 'A reformed hunter becomes involved in a deadly game of cat and mouse when he and the local sheriff set out to track a vicious killer who may have kidnapped his daughter years ago.',
    relaseDate: '2021-01-28',
    runtime: '104 min',
    popularity: 116557,
    poster: 'https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg',
    cinema: 'Cinemex, Hiflix, CineOne, CinemaXXI, Cinebay'
  },
  {
    id: 11,
    language: 'en',
    genre: 'Drama, Comedy',
    director: 'Doni Gunn',
    actors: 'Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel',
    name: 'Let Him Go',
    synopsis: 'Following the loss of their son, a retired sheriff and his wife leave their Montana ranch to rescue their young grandson from the clutches of a dangerous family living off the grid in the Dakotas.',
    relaseDate: '2020-11-05',
    runtime: '101 min',
    popularity: 95967,
    poster: 'https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg',
    cinema: 'Cinemex, Hiflix, CinemaXXI, Cinebay, Olympia Cinema'
  },
  {
    id: 12,
    language: 'en',
    genre: 'Sci-Fi',
    director: 'Popeye Gunn',
    actors: 'Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel',
    name: 'Pinocchio',
    synopsis: 'In this live-action adaptation of the beloved fairytale, old woodcarver Geppetto fashions a wooden puppet, Pinocchio, who magically comes to life. Pinocchio longs for adventure and is easily led astray, encountering magical beasts, fantastical spectacles, while making friends and foes along his journey. However, his dream is to become a real boy, which can only come true if he finally changes his ways.',
    relaseDate: '2019-12-19',
    runtime: '106 min',
    popularity: 89125,
    poster: 'https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg',
    cinema: 'Cinemex, Hiflix, CineOne, CinemaXXI'
  },
  {
    id: 13,
    language: 'en',
    genre: 'Horor',
    director: 'Mr Bean',
    actors: 'Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel',
    name: 'Yummy',
    synopsis: 'Six friends hire a medium to hold a séance via Zoom during lockdown — but they get far more than they bargained for as things quickly go wrong. When an evil spirit starts invading their homes, they begin to realize they might not survive the night.',
    relaseDate: '2020-12-04',
    runtime: '131 min',
    popularity: 89109,
    poster: 'https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg',
    cinema: 'Cinemex, Olympia Cinema'
  },
  {
    id: 14,
    language: 'en',
    genre: 'Horor',
    director: 'Zack Kilby',
    actors: 'Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel',
    name: 'Host',
    synopsis: 'Six friends hire a medium to hold a séance via Zoom during lockdown — but they get far more than they bargained for as things quickly go wrong. When an evil spirit starts invading their homes, they begin to realize they might not survive the night.',
    relaseDate: '2020-12-04',
    runtime: '133 min',
    popularity: 128132,
    poster: 'https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg',
    cinema: 'Cinebay, Olympia Cinema'
  },
  {
    id: 15,
    language: 'en',
    genre: 'Horor',
    director: 'Jonathan Gunn',
    actors: 'Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel',
    name: 'Songbird',
    synopsis: 'Six friends hire a medium to hold a séance via Zoom during lockdown — but they get far more than they bargained for as things quickly go wrong. When an evil spirit starts invading their homes, they begin to realize they might not survive the night.',
    relaseDate: '2020-12-04',
    runtime: '126 min',
    popularity: 124132,
    poster: 'https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg',
    cinema: 'Cinemex, Hiflix, CineOne, CinemaXXI, Cinebay'
  },
  {
    id: 16,
    language: 'en',
    genre: 'Action, Adventure',
    director: 'James Spalker',
    actors: 'Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel',
    name: 'The Marksman',
    synopsis: 'A rancher on the Arizona border becomes the unlikely defender of a young Mexican boy desperately fleeing the cartel assassins whove pursued him into the U.S.',
    relaseDate: '2021-01-15',
    runtime: '116 min',
    popularity: 71145,
    poster: 'https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg',
    cinema: 'Cinemex, Hiflix, CinemaXXI, Cinebay, Olympia Cinema'
  },
  {
    id: 17,
    language: 'en',
    genre: 'Action, Adventure',
    director: 'Branidon',
    actors: 'Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel',
    name: 'My Neighbor Totoro',
    synopsis: 'A rancher on the Arizona border becomes the unlikely defender of a young Mexican boy desperately fleeing the cartel assassins whove pursued him into the U.S.',
    relaseDate: '2021-01-15',
    runtime: '131 min',
    popularity: 71145,
    poster: 'https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg',
    cinema: 'Hiflix, CineOne, CinemaXXI, Cinebay'
  },
  {
    id: 18,
    language: 'en',
    genre: 'Adventure',
    director: 'James Walker',
    actors: 'Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel',
    name: 'News of the World',
    synopsis: 'Separated from her fiance after sneaking onto a restricted slope, Mia, a free riding snowboarder, must survive not only against nature, but the masked snowmobile rider in black whos out for her blood.',
    relaseDate: '2021-01-28',
    runtime: '132 min',
    popularity: 71519,
    poster: 'https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg',
    cinema: 'Cinemex, Hiflix, CineOne'
  },
  {
    id: 19,
    language: 'en',
    genre: 'Action, Criminal',
    director: 'Scot Gunn',
    actors: 'Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel',
    name: 'Money Plane',
    synopsis: 'A professional thief with $40 million in debt and his familys life on the line must commit one final heist - rob a futuristic airborne casino filled with the worlds most dangerous criminals.',
    relaseDate: '2020-09-29',
    runtime: '106 min',
    popularity: 61006,
    poster: 'https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg',
    cinema: 'Hiflix, Cinebay, Olympia Cinema'
  },
  {
    id: 20,
    language: 'en',
    genre: 'Adventure',
    director: 'James Gunn',
    actors: 'Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel',
    name: 'Let It Snow',
    synopsis: 'Separated from her fiance after sneaking onto a restricted slope, Mia, a free riding snowboarder, must survive not only against nature, but the masked snowmobile rider in black whos out for her blood.',
    relaseDate: '2021-01-28',
    runtime: '146 min',
    popularity: 71519,
    poster: 'https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg',
    cinema: 'Cinemex, Hiflix, CineOne, CinemaXXI'
  }
]
